name: Python package

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref_name }}
    - name: Sync to latest branch tip
      run: |
        git fetch origin "${GITHUB_REF_NAME}"
        git checkout "origin/${GITHUB_REF_NAME}"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest semgrep build twine
        python -m pip install -e .[dev]

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=26 --max-line-length=320 --statistics

    - name: Run tests
      run: |
        python -m pytest || [ $? -eq 5 ]

    - name: Security scan with Semgrep
      run: |
        semgrep --config=p/r2c

    - name: Build the package
      run: python -m build --sdist --wheel

    - name: Check and publish
      if: success()
      run: |
        twine check dist/*
        twine upload dist/*
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}

    - name: Upload artifacts
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: dist-3.12-ubuntu-latest
        path: dist/*
        if-no-files-found: error
        retention-days: 90
